# 1224

In [ ]:
a = 10
b = a

print(a)
print(b)

In [ ]:
print('주소값 대입', id(a), print(id(b)))

In [ ]:
a3 = 4.24e-3
a4 = 0o177

In [ ]:
print(a3,a4)

In [ ]:
s = 'korea'

print(s+s)
print(s[0:])
print(s[-2:])

In [ ]:
print(s.capitalize())

In [ ]:
print(s.find('r'))
print(s.isdigit())
print('123'.isdigit())

print(s)

In [ ]:
i =[4,7,8]

sum(i)

In [ ]:
num1 = input('num1')
num2 = input('num2')



sum = int(num1) + int(num2)


q = sum //2
re = sum %2

if re ==0:
    print('짝수')
else:
    print('홀수')
    


In [ ]:
x = 300
def myfunc():
    x=200
    print(x)
myfunc()
print(x)
    

In [ ]:
myfunc()
print

In [ ]:
ran = int(input('정수'))%3

if ran ==0:
    print('가위')
elif ran ==1:
    print('바위')
elif ran ==2:
    print('보')

In [ ]:
import random

random.seed(1000)

print(random.randint(1,5))

In [ ]:
def caic(a,b):
    return a+b,a*b
x,y = caic(3,5)

In [ ]:
print(x,y)

In [ ]:

color = input('색')
ㅡㅐㅇㄷ

In [ ]:
###

In [ ]:
cost = eval(input('총비용'))
revenue = eval(input('총수익'))
if cost == revenue:
    result = '손익분기점'
else:
    if cost< revenue:
        profit = revenue - cost
        result = '순수익 = {0:,.2f}.'.format(round(profit,2))
    else:
        loss = cost - revenue
        result = '순손실 = {0:,.2f}.'.format(round(loss,2))
        
print(result)

# 1226


In [ ]:
x =5
ans = 'non-negative' if x>=0 else 'negative'
print(ans)

In [ ]:
city = " "
if city:
    print('empty city')

In [ ]:
import datetime
dt = datetime.datetime.now()
print(dt)
print()


In [ ]:
age = input('age')

In [ ]:
year = int(age[0:4])
month = int(age[4:6])
day = int(age[6:])

year_diff = dt.year - year
month_diff = dt.month - month
day_diff = dt.day - day

if day_diff<0:
    month_diff-=1
if month_diff<0:
    year_diff-=1
print('당신의 나이는', year_diff+1)

if year_diff<18:
    print('under')
else:
    print("adult")

In [ ]:
elements =['earth','air','fire','water']
for i in elements:
    print(i)

In [ ]:
for i in range(0,10,2):
    print(i, end =" ")
    

In [ ]:
for i in range(4):
    print(i)
    print(elements[i])

In [ ]:
sum = 10
for x in range(1,11):
    sum +=x
print(sum)

In [ ]:
for x in range(2,10):
    print()
    for y in range(2,10):
        print(y,"*",x,'=',x*y,'\t',end =" ")

In [ ]:
[i for  i in range(10)]

In [ ]:
[i **2 for i in range(10)]

In [ ]:
rows = range(1,5)
cols = range(10,15)
vectors = [(r,c) for r in rows for c in cols]

In [ ]:
score = int(input("enter score"))

if score>= 100:
    print('A')
elif score>=80:
    print('b')
else:
    print('fail')

In [ ]:
# 이름 영 수 점수입력하기

total =[]

for i in range(2):
    final =[]
    name = input("name :")
    eng = int(input('eng'))
    math = int(input('math'))
    final.append(name)
    final.append(eng)
    final.append(math)
    total.append(final)
print(total)

In [4]:
def getkey(a1):
    return a1[1]
    total.sort(key = getkey)
    total.sort(key=getkey,reverse = True)

In [6]:
print(total)

[['seo', 100, 50], ['yoo', 40, 690]]


In [7]:
total.sort(key = lambda row: row[1], reverse = True)

In [ ]:
#문제 1
#제곱미터로 입력되는 아파트 면적을 평형으로 계산하여 종류 판정
#(30평을 기준으로 판정) 하는 프로그램 작성
#소형(17평) 중소형(25평) 중형(30평)
#평형수 = 제곱미터 / 3.305

In [9]:
size = int(input(' size : (m2)'))

apt = size / 3.305


if apt >= 30:
    print('중')
elif apt >=25:
    print("중소")
else:
    print('소')

 size : (m2)100
중


In [ ]:
#문제 2 
# 날 수를 입력하면 이를 초로 변경하는 프로그램 작성


In [13]:

days = int(input("enter the number of days you want to convert to seconds"))

seconds = days *24 * 60 * 60

print(days,"days converted to",seconds,'seconds')

enter the number of days you want to convert to seconds5
5 days converted to 432000 seconds


In [ ]:
#문제 3
#소득세 계산 : 소득 세율표를 구해보고 이를 이용하여 소득이 들어오면 세금이 
#             얼마인지 계산해 보세요 ( 연봉, 단순히 세율만 적용)
#1천만원 미만시 연봉의 9.5% / 1천 - 4천 : 19%  / 4천 - 8천 :  28% / 8천이상 : 37%


In [19]:
income = int(input("tax calculator depends on income")) 


if income <1000:
    tax = income * 0.095
elif income <4000:
    tax =  (1000 * 0.095) + (income - 1000) *0.19
else :
    tax = (4000 * 0.28) + (income - 4000) * 0.37
    
print('your tax:', tax)
    


tax calculator depends on income100000
your tax: 36640.0


# 1227

In [21]:
def reg(x):
    return x ** 2

reg(9)

81

In [24]:
def abc(a,b,c):
    return a*b + c

abc(2,3,4)

10

In [28]:
def a(x,y):
    return x+y

In [29]:
def change(a,b,c):
    return a(b,c)

change(a,2,3)


5

In [30]:
def repeat(*args):
    for i in args:
        print(i,end= " ")
    print()
print('시작')





시작


In [31]:
b = [1,3,4,5]

In [32]:
repeat(b)

[1, 3, 4, 5] 


In [38]:
def testa(f,*args,**kwargs):
    print("args is", args)
    print('kwargs is',kwargs)
    print('hi i am going to call %s'% f)
    return f(*args, ** kwargs)


def g(x,y):
    return x + y


testa(g,5,3)

args is (5, 3)
kwargs is {}
hi i am going to call <function g at 0x000002C6465EE288>


8

In [43]:
def all(x,y):
    return x + y
addi = lambda y: all(5,y)
print(addi(10))


15


In [45]:
def facto(n):
    sum = 1 
    for i in range(n,1,-1):
        sum *= i
    return sum

In [46]:
facto(3)

6

In [ ]:
def power(r,n):
    value =1
    for i in range(1, n + 1):
        value = r * value
    return value


In [49]:
(lambda x:x*x)(5)

25

In [ ]:
#성적 프로그램을 입력, 처리 , 출력 함수를 이용해서 구현하시오
# 이름,국어,영어, 수학, 총점,평균

#입력

#성적 프로그램을 입력, 처리 , 출력 함수를 이용해서 구현하시오
# 이름,국어,영어, 수학, 총점,평균

#list에 담아서 보기 


In [11]:
score_info=[]

def score():
    name = input('name:')
    kor = int(input('kor:'))
    math = int(input('math:'))
    eng = int(input('eng :'))
    score_info.append(name)
    score_info.append(kor)
    score_info.append(math)
    score_info.append(eng)
    return score_info

def process(score_info):
    total = sum(score_info[1:])
    avg = total/3
    score_info.append(total)
    score_info.append(avg)
    return score_info

def result(score_info):
    for i in range(len(score_info)):
        print(score_info[i],end="\t")
        
        

In [12]:
result(process(score()))

name:최
kor:10
math:10
eng :10
최	10	10	10	30	10.0	

# 1230

In [8]:
width = 10
height =150



In [9]:
class Triangle:
    def setdata(self,width,height):
        self.width = width
        self.height =height
    def area(self):
        return self.width*height/2
tri1 =Triangle()
tri1.setdata(10,20)

In [10]:
print(tri1.width,tri1.height,tri1.area())

10 20 750.0


In [12]:
class Myclass(object):
    """ex of class"""
    i = 12345
    def __init(self):
        self.i=54321
        num =100
    def f(self):
        return self.i

In [14]:
Myclass.__doc__

'ex of class'

In [ ]:
import math
class point:
    def __init__(self,x,y):
        self.x =x
        self.y =y
    def __str__(self):
        return "좌표는 (%d,%d)"%(self.x,self.y)
    

# 0106

In [16]:
import flask
import matplotlib 
import numpy as np

print(np.__version__)
def pprint(arr):
    print('type:{}'.format(type(arr)))
    print('shape:{},dimension:{},dtype:{}'.format(arr.shape,arr.ndim,arr.dtype))
    print('arrays data:\n',arr)

arr =[1,2,3]
a = np.array([1,2,3])        
          

1.16.5


In [22]:

print(np.zeros((3,4)))
print(np.ones((2,3,4),dtype=np.int16))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [24]:
a = np.arange(11,36)

print(a)

[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35]


In [26]:
print(a.ndim)
print(a.nbytes)

1
100


In [29]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [31]:
print(arr3d[0])

print(arr3d[0][0])

[[1 2 3]
 [4 5 6]]
[1 2 3]


In [34]:
z = np.arange(36)
print(z)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]


In [36]:
z1=z.reshape(6,6)
print(z1)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [42]:
import numpy as np
f1 = np.array([[1,2],[3,4]])
f2 = np.array([[2,2],[3,4]])

print('f1',f1)
print('f2',f2)
print()
print(f1+f2)
print()
print(f1*f2)

f1 [[1 2]
 [3 4]]
f2 [[2 2]
 [3 4]]

[[3 4]
 [6 8]]

[[ 2  4]
 [ 9 16]]


In [51]:
a = np.array([[2,1,-2],[3,0,1],[1,1,-1]])
print(a)
print()
b = np.transpose(np.array([[-3,5,-2]]))

print(b)

x = np.linalg.solve(a,b)
print()
print(x)

[[ 2  1 -2]
 [ 3  0  1]
 [ 1  1 -1]]

[[-3]
 [ 5]
 [-2]]

[[ 1.]
 [-1.]
 [ 2.]]
